env:
    es6: true
    node: true
    mocha: true
extends: 
    - 'eslint:recommended'
    - 'plugin:react/recommended'
parserOptions:
    ecmaVersion: 8
    sourceType: module
rules:
    indent:
        - error
        - 2
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-unused-vars:
        - error
        - args: none
    no-console: warn
    curly: error
    eqeqeq: error
    no-throw-literal: error
    strict: error
    no-var: error
    dot-notation: error
    no-tabs: error
    no-trailing-spaces: error
    no-use-before-define: error
    no-useless-call: error
    no-with: error
    operator-linebreak: error
    require-jsdoc:
        - warn
        - require:
            ClassDeclaration: true
            MethodDefinition: true
            FunctionDeclaration: true
    valid-jsdoc:
        - error
        - requireReturn: false
    yoda: error
